-- ============================== migration: itinerary field + per-tour FAQs ==============================
-- Run this ONCE in the Supabase SQL Editor (after schema.sql / seed_data.sql already applied).

alter table tours add column if not exists itinerary text;

-- Seed each tour's existing 3 FAQ items into the faqs table (page = tour slug),
-- so the admin FAQ editor starts populated with exactly what's live today.
INSERT INTO faqs (id, page, question, answer) VALUES ('4c7c2134-8ce3-fc29-ccbc-5817d6cadd3b', 'village-guided-bike-tour', 'How long does Village Guided Bike Tour take?', 'Most of our bike tours run as a half-day experience. Contact us and we''ll confirm exact timing for Village Guided Bike Tour.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('cbf30cb9-3661-c7c6-a76f-c1d5c7b0e780', 'village-guided-bike-tour', 'Is Village Guided Bike Tour suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('8260270f-35af-0e6e-c0b8-601178a2ccd0', 'village-guided-bike-tour', 'Can I book Village Guided Bike Tour for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('0045b5c4-e538-a64d-8af1-9173e2ffa770', 'kaya-kinondo-sacred-forest', 'How long does Kaya Kinondo Sacred Forest take?', 'Most of our bike tours run as a half-day experience. Contact us and we''ll confirm exact timing for Kaya Kinondo Sacred Forest.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('6661a000-7911-caa9-be24-08f85419ed5a', 'kaya-kinondo-sacred-forest', 'Is Kaya Kinondo Sacred Forest suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('e1b59903-528c-701b-073e-0513e2d10a0c', 'kaya-kinondo-sacred-forest', 'Can I book Kaya Kinondo Sacred Forest for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('f616e136-5211-60ff-ba99-3e0369481101', 'giraffe-feeding-adventure', 'How long does Giraffe Feeding Adventure take?', 'Most of our bike tours run as a half-day experience. Contact us and we''ll confirm exact timing for Giraffe Feeding Adventure.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('71c335ce-cb07-61da-e726-a088e8497a71', 'giraffe-feeding-adventure', 'Is Giraffe Feeding Adventure suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('326ff99d-4ef2-d8ab-be58-077f175b0097', 'giraffe-feeding-adventure', 'Can I book Giraffe Feeding Adventure for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('7814c51c-5781-c617-3c86-5f23d1a1656f', 'elephant-sporting', 'How long does Elephant Sporting take?', 'Most of our bike tours run as a half-day experience. Contact us and we''ll confirm exact timing for Elephant Sporting.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('286414be-1a01-1bba-4d1d-e9f746c94d26', 'elephant-sporting', 'Is Elephant Sporting suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('8e18e92f-93cd-84aa-eec6-4fd24a71d8d4', 'elephant-sporting', 'Can I book Elephant Sporting for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('487daee4-7bb5-a79f-3515-c75f42897ce2', 'bush-tour', 'How long does Bush Tour take?', 'Most of our bike tours run as a half-day experience. Contact us and we''ll confirm exact timing for Bush Tour.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('939693a1-92f1-4fc4-8f54-eeb1c9b4e85b', 'bush-tour', 'Is Bush Tour suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('9adc330a-7e93-dc7a-d25f-f7d13bf4057f', 'bush-tour', 'Can I book Bush Tour for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('644ea3ee-88bd-f6fe-f85b-ee547e3043d3', 'mangrove-sundowner', 'How long does Mangrove Tour (Sundowner) take?', 'Most of our marine excursions run as a half-day experience. Contact us and we''ll confirm exact timing for Mangrove Tour (Sundowner).') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('668cbc84-be6d-b9e7-75a4-808339427f23', 'mangrove-sundowner', 'Is Mangrove Tour (Sundowner) suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('8677e370-e533-cd4d-a72c-fea4ed9c7bde', 'mangrove-sundowner', 'Can I book Mangrove Tour (Sundowner) for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('e8ce9893-5a53-489d-57d0-7b491ca2a648', 'full-day-private-dolphin-tour', 'How long does Full Day Private Dolphin Tour take?', 'This is a full-day private experience — get in touch and we''ll help you plan your ideal start time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('92e5f462-e6b7-1659-f4a8-6920580a3e88', 'full-day-private-dolphin-tour', 'Is Full Day Private Dolphin Tour suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('5acab407-224b-effc-8496-a4ad482926e1', 'full-day-private-dolphin-tour', 'Can I book Full Day Private Dolphin Tour for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('8b7f9e31-0507-6a9e-1bef-d380c80c2766', 'camel-adventure', 'How long does Camel Adventure take?', 'Most of our marine excursions run as a half-day experience. Contact us and we''ll confirm exact timing for Camel Adventure.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('af074e1b-39b6-612d-91d9-30d9a76e0ebd', 'camel-adventure', 'Is Camel Adventure suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('26ca5324-d195-da47-ed0a-b4f8be022a9d', 'camel-adventure', 'Can I book Camel Adventure for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('528b04f8-b132-4373-54d1-d84b05ec72b1', 'beach-tour', 'How long does Beach Tour take?', 'Most of our marine excursions run as a half-day experience. Contact us and we''ll confirm exact timing for Beach Tour.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('113b24dc-3864-03e4-dc9b-22d146497d8a', 'beach-tour', 'Is Beach Tour suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('d7b70e1a-b842-306e-f479-38d3b7ca6c63', 'beach-tour', 'Can I book Beach Tour for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('1d14cf99-1222-1f7b-fb04-382ba1daaae5', 'snake-show-and-school', 'How long does Snake Show And School take?', 'Most of our forest excursions run as a half-day experience. Contact us and we''ll confirm exact timing for Snake Show And School.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('6ec9b90c-b6bf-3d98-a0f8-b742cc01faee', 'snake-show-and-school', 'Is Snake Show And School suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('462db4dd-fc8e-881f-183e-1244810fb4d6', 'snake-show-and-school', 'Can I book Snake Show And School for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('4643b471-6700-c29d-76c4-03c96926bd9c', 'ruins-of-mnarani', 'How long does Ruins of Mnarani take?', 'Most of our forest excursions run as a half-day experience. Contact us and we''ll confirm exact timing for Ruins of Mnarani.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('59bd1736-f759-286d-69a1-ea225c73ae93', 'ruins-of-mnarani', 'Is Ruins of Mnarani suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('96096575-06db-182b-7ac1-407e5e39c051', 'ruins-of-mnarani', 'Can I book Ruins of Mnarani for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('6fe795b5-6ebf-e201-9307-793a66fe5ead', 'monkey-trails-and-conservation-centre', 'How long does Monkey Trails And Conservation Centre take?', 'Most of our forest excursions run as a half-day experience. Contact us and we''ll confirm exact timing for Monkey Trails And Conservation Centre.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('ef5aae04-f241-c335-bbbf-a676dc6ba16e', 'monkey-trails-and-conservation-centre', 'Is Monkey Trails And Conservation Centre suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('b38640f3-1cf4-7df9-f0fd-b7d132b629b2', 'monkey-trails-and-conservation-centre', 'Can I book Monkey Trails And Conservation Centre for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('0a4675ef-6ab7-0630-5c69-bb132afb0684', 'gede-ruins-tour', 'How long does Gede Ruins Tour take?', 'Most of our forest excursions run as a half-day experience. Contact us and we''ll confirm exact timing for Gede Ruins Tour.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('bf7610cd-22ec-047a-0e08-4383d911213b', 'gede-ruins-tour', 'Is Gede Ruins Tour suitable for beginners?', 'Yes — our guides tailor the pace to the group, so it''s a great option whether you''re an experienced adventurer or trying it for the first time.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('46560dcf-750d-723b-c8cd-415561e78fa9', 'gede-ruins-tour', 'Can I book Gede Ruins Tour for a private group?', 'Absolutely — get in touch with your group size and preferred date and we''ll arrange it.') ON CONFLICT (id) DO NOTHING;
