-- ============================== tours ==============================
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('village-guided-bike-tour', 'Bike Tours', 'Village Guided Bike Tour', ARRAY['Diani','Watamu']::text[], 'Ride through the heart of local village life on this guided bike tour through Diani and Watamu. Your local guide leads the way past homesteads, markets, and everyday coastal life you won''t find in a guidebook.', ARRAY['A local, English-speaking guide','Bike, helmet, and lock','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities','Hotel pickup outside the core area']::text[], ARRAY['Sunscreen, hat, and sunglasses','Comfortable closed shoes','Camera or phone for photos']::text[], ARRAY['../images/tour-village.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('kaya-kinondo-sacred-forest', 'Bike Tours', 'Kaya Kinondo Sacred Forest', ARRAY['Diani','Tuk Tuk']::text[], 'Ride out to Kaya Kinondo, one of the coast''s sacred Mijikenda forest sites, protected by the local community for generations.', ARRAY['A local guide','Bike, helmet, and lock','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Sunscreen and a hat','Comfortable closed shoes']::text[], ARRAY['../images/tour-kaya-kinondo.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('giraffe-feeding-adventure', 'Bike Tours', 'Giraffe Feeding Adventure', ARRAY['Diani','Forest Excursions']::text[], 'Cycle to one of the coast''s best-loved wildlife stops for a close encounter with giraffes — hand-feeding included.', ARRAY['A local guide','Bike, helmet, and lock','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Camera or phone for photos','Comfortable closed shoes']::text[], ARRAY['../images/tour-giraffe.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('elephant-sporting', 'Bike Tours', 'Elephant Sporting', ARRAY['Tuk Tuk','Watamu']::text[], 'Head toward Watamu for a ride centred on spotting elephants in their natural surroundings — a highlight for wildlife lovers.', ARRAY['A local guide','Bike, helmet, and lock (or tuk tuk & driver)','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Sunscreen and a hat','Camera or phone for photos']::text[], ARRAY['../images/tour-elephant.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('bush-tour', 'Bike Tours', 'Bush Tour', ARRAY['Diani','Kilifi','Tuk Tuk','Watamu']::text[], 'Get off the beaten track on a rugged ride through the coastal bush between Diani, Kilifi, and Watamu.', ARRAY['A local guide','Bike, helmet, and lock','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Comfortable closed shoes','Cash for personal spending']::text[], ARRAY['../images/tour-bush.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('mangrove-sundowner', 'Marine Excursions', 'Mangrove Tour (Sundowner)', ARRAY['Diani','Kilifi','Watamu']::text[], 'Drift through quiet mangrove channels as the sun sets over the water, one of the coast''s most peaceful ways to end the day.', ARRAY['A local boat guide','Life jacket','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['A light jacket for the evening','Camera or phone for photos']::text[], ARRAY['../images/marine-mangrove.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('full-day-private-dolphin-tour', 'Marine Excursions', 'Full Day Private Dolphin Tour', ARRAY['Diani']::text[], 'Spend a full day out on the water with a private boat, searching the Indian Ocean for dolphins.', ARRAY['A local boat guide','Life jacket','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Swimwear and a change of clothes','Sunscreen and a hat']::text[], ARRAY['../images/marine-dolphin.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('camel-adventure', 'Marine Excursions', 'Camel Adventure', ARRAY['Diani']::text[], 'Trade two wheels for four legs with a relaxed camel ride along the white sand of Diani beach.', ARRAY['An experienced local handler','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Sunscreen and a hat','Camera or phone for photos']::text[], ARRAY['../images/marine-camel.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('beach-tour', 'Marine Excursions', 'Beach Tour', ARRAY['Diani']::text[], 'A guided walk or ride along Diani''s beachfront, taking in the coastline at an easy pace.', ARRAY['A local guide','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Sunscreen and a hat','Comfortable footwear']::text[], ARRAY['../images/marine-beach.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('snake-show-and-school', 'Forest Excursions', 'Snake Show And School', ARRAY['Diani','Watamu']::text[], 'An educational, family-friendly stop to see the coast''s native snake species up close in a safe, controlled setting.', ARRAY['A local guide','Entry to the site','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Comfortable closed shoes','Camera or phone for photos']::text[], ARRAY['../images/forest-snake-show.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('ruins-of-mnarani', 'Forest Excursions', 'Ruins of Mnarani', ARRAY['Kilifi']::text[], 'Explore the historic Mnarani ruins overlooking Kilifi Creek, remnants of a Swahili settlement steeped in coastal history.', ARRAY['A local guide','Entry to the site','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Insect repellent','Sunscreen and a hat']::text[], ARRAY['../images/forest-mnarani-ruins.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('monkey-trails-and-conservation-centre', 'Forest Excursions', 'Monkey Trails And Conservation Centre', ARRAY['Diani']::text[], 'Wander forest trails home to local monkey populations, with a conservation-focused guide sharing insight into the ecosystem.', ARRAY['A local guide','Entry to the site','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Insect repellent','Comfortable closed shoes']::text[], ARRAY['../images/forest-monkey-trails.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO tours (id, category, title, location_tags, description, included, excluded, carry, images, status) VALUES ('gede-ruins-tour', 'Forest Excursions', 'Gede Ruins Tour', ARRAY['Watamu']::text[], 'Discover the ancient Swahili ruins of Gede, hidden within the forest near Watamu and among the coast''s best-preserved historic sites.', ARRAY['A local guide','Entry to the site','Bottled water']::text[], ARRAY['Personal travel insurance','Tips and gratuities']::text[], ARRAY['Insect repellent','Comfortable closed shoes']::text[], ARRAY['../images/forest-gede-ruins.svg']::text[], 'Published') ON CONFLICT (id) DO NOTHING;

-- ============================== bookings ==============================
INSERT INTO bookings (id, type, interest, name, email, whatsapp, office, duration, bikes, guests, date, submitted_at, status) VALUES ('bf1e1e48-b9dd-c624-f771-f5208bc25dd5', 'rental', 'Bike Rental', 'Amina Yusuf', 'amina@example.com', '+254711223344', 'Watamu (Jiweleupe)', 'Full Day', '{"Electric Bike": 2, "Mountain Bike": 1, "Manual Bike": 0, "Kids Bike": 3}'::jsonb, NULL, '2026-09-10', '2026-08-10T09:20:00Z', 'New') ON CONFLICT (id) DO NOTHING;
INSERT INTO bookings (id, type, interest, name, email, whatsapp, office, duration, bikes, guests, date, submitted_at, status) VALUES ('744e9b7a-3236-a0c8-008a-137d9ea281a9', 'rental', 'Bike Rental', 'Tom Fischer', 'tom.fischer@example.com', '+491701234567', 'Diani Bazaar', 'Half Day', '{"Electric Bike": 0, "Mountain Bike": 2, "Manual Bike": 0, "Kids Bike": 0}'::jsonb, NULL, '2026-08-22', '2026-08-08T14:05:00Z', 'Contacted') ON CONFLICT (id) DO NOTHING;
INSERT INTO bookings (id, type, interest, name, email, whatsapp, office, duration, bikes, guests, date, submitted_at, status) VALUES ('9b8c9a0c-e570-c53a-27e6-925c7359acc0', 'rental', 'Bike Rental', 'Priya Shah', 'priya.shah@example.com', '+919812345670', 'Diani Bazaar', 'Full Day', '{"Electric Bike": 1, "Mountain Bike": 0, "Manual Bike": 1, "Kids Bike": 0}'::jsonb, NULL, '2026-08-19', '2026-08-05T11:40:00Z', 'Confirmed') ON CONFLICT (id) DO NOTHING;
INSERT INTO bookings (id, type, interest, name, email, whatsapp, office, duration, bikes, guests, date, submitted_at, status) VALUES ('4ad04dc8-e09e-5361-bbbb-6addbc8e7393', 'rental', 'Bike Rental', 'Jonas Berg', 'jonas.berg@example.com', '+46701234567', 'Watamu (Jiweleupe)', 'Half Day', '{"Electric Bike": 0, "Mountain Bike": 0, "Manual Bike": 4, "Kids Bike": 2}'::jsonb, NULL, '2026-09-02', '2026-08-11T07:55:00Z', 'New') ON CONFLICT (id) DO NOTHING;
INSERT INTO bookings (id, type, interest, name, email, whatsapp, office, duration, bikes, guests, date, submitted_at, status) VALUES ('8767f761-cd4f-5182-be99-d220ea252210', 'tour', 'Full Day Private Dolphin Tour', 'Laura Kim', 'laura.kim@example.com', '+821012345678', NULL, NULL, NULL, 2, '2026-08-27', '2026-08-09T10:15:00Z', 'New') ON CONFLICT (id) DO NOTHING;
INSERT INTO bookings (id, type, interest, name, email, whatsapp, office, duration, bikes, guests, date, submitted_at, status) VALUES ('8853ac39-bfc2-5dfa-65ab-38fb575bc225', 'tour', 'Village Guided Bike Tour', 'Peter van Dijk', 'peter.vd@example.com', '+31612345678', NULL, NULL, NULL, 4, '2026-08-18', '2026-08-06T16:30:00Z', 'Contacted') ON CONFLICT (id) DO NOTHING;

-- ============================== partners ==============================
INSERT INTO partners (id, name, logo) VALUES ('1b2257cc-a54f-cc42-62d7-b1e1ba3dcbbb', 'Partner One', '../images/partner-logo-1.svg') ON CONFLICT (id) DO NOTHING;
INSERT INTO partners (id, name, logo) VALUES ('bf032aaa-f35b-c795-43d0-a8b6c6502e4b', 'Partner Two', '../images/partner-logo-2.svg') ON CONFLICT (id) DO NOTHING;
INSERT INTO partners (id, name, logo) VALUES ('e4e05ba1-6d30-37ab-93b0-de9c0c845ed5', 'Partner Three', '../images/partner-logo-3.svg') ON CONFLICT (id) DO NOTHING;
INSERT INTO partners (id, name, logo) VALUES ('07963d39-fea5-49c1-5c14-eb947f2a938e', 'Partner Four', '../images/partner-logo-4.svg') ON CONFLICT (id) DO NOTHING;

-- ============================== faqs ==============================
INSERT INTO faqs (id, page, question, answer) VALUES ('36876350-d8b6-4f30-5a26-8e591ec4b791', 'about', 'What types of bikes do you offer for rent?', 'We offer a variety of bikes for rent to suit every rider''s needs and preferences. Our selection includes classic bicycles for leisurely rides, mountain bikes for off-road adventures, and electric bikes for effortless exploration.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('34229832-b246-64f1-ee48-1355be31377d', 'about', 'Do you provide guided tours for bike excursions?', 'Absolutely! Our bike excursions are led by experienced local guides who will accompany you on your adventure, sharing insights into the area''s history, culture, and natural beauty.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('fbe1b3cf-8cda-f0c0-a7f4-70fb4e06c245', 'about', 'Are helmets provided with bike rentals?', 'Yes, safety is our top priority. We provide helmets with every bike rental to ensure that our riders can explore Diani with peace of mind.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('004ea661-7a95-ce94-f7ba-bc3c5495f151', 'about', 'Can I customize a day trip to suit my interests?', 'Of course! We understand that every traveler is unique, which is why we offer customizable day trips tailored to your preferences. Whether you''re interested in biking, cultural experiences, or outdoor adventures, we''ll work with you to create the perfect itinerary for an unforgettable day in Diani.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('f85e9bc5-889c-aa90-9749-f6312918050a', 'rentals', 'What types of bikes can I rent?', 'We offer Electric, Mountain, Manual, and Kids bikes, so there''s an option whether you want an effortless ride, a rugged off-road trail, a relaxed cruise, or a safe first ride for younger riders.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('42422b8a-ac94-4a53-af06-5bc00d677f10', 'rentals', 'What''s included with every rental?', 'Every rental comes with a helmet and a bike lock, and you can add an optional front basket at no extra request — handy for beach bags or shopping trips.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('0a8a969c-78cf-2b6c-8da9-350c1576ad88', 'rentals', 'Do you offer half-day and full-day rates?', 'Yes — every bike type is available on a half-day or full-day rate. See the pricing above for the current rates per bike.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('1b0665d8-48a7-8a41-49d9-711e8a4fb73e', 'rentals', 'Can I rent a bike without booking a guided tour?', 'Absolutely — self-guided rentals are available if you''d rather explore at your own pace. If you''d prefer a local guide, take a look at our Bike Tours.') ON CONFLICT (id) DO NOTHING;
INSERT INTO faqs (id, page, question, answer) VALUES ('a42beecd-42d8-0591-cb3a-5d537087db80', 'rentals', 'Are helmets provided for kids too?', 'Yes, safety is our top priority for every rider — including kids. Every Kids Bike rental comes with a properly fitted helmet.') ON CONFLICT (id) DO NOTHING;

-- ============================== reviews ==============================
INSERT INTO reviews (id, reviewer, quote, rating, source) VALUES ('0fb61e2f-4cfd-adc8-9f26-9a0f107b076a', 'Reviewer Name (placeholder)', 'Placeholder — client to paste a real review quote here.', 5, 'TripAdvisor') ON CONFLICT (id) DO NOTHING;
INSERT INTO reviews (id, reviewer, quote, rating, source) VALUES ('8a67d694-b0b8-34e6-bf13-7861c7d90931', 'Reviewer Name (placeholder)', 'Placeholder — client to paste a real review quote here.', 5, 'Google Maps') ON CONFLICT (id) DO NOTHING;
INSERT INTO reviews (id, reviewer, quote, rating, source) VALUES ('90a18a7c-90b0-4ef0-866a-cfcabf71af0f', 'Reviewer Name (placeholder)', 'Placeholder — client to paste a real review quote here.', 4, 'TripAdvisor') ON CONFLICT (id) DO NOTHING;

-- ============================== team ==============================
INSERT INTO team (id, name, designation, photo, bio) VALUES ('e7523c4f-89da-a638-39be-534f0e22ae22', 'Masha Kirao', 'Founder & Team Leader', '../images/Masha-Diani-BIkes-team-Founder.jpg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('c632962e-a376-1e13-6de4-e1228350e4b2', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-1.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('f92f537b-1772-b251-583f-3f180fce41c5', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-2.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('f410a946-6e62-c128-06bf-5d14208f04d3', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-3.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('2003c6a0-a99f-e5ba-29a6-e6a658cb3dff', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-4.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('50ac07d1-bf6a-f966-f6bf-7a97c7afa107', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-5.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('6fbb9a3c-d777-1cbb-125b-f1703fe4aef2', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-6.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('dacf9cf2-c119-9e16-9b6e-f355b975b3aa', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-1.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('67b0bc38-ae22-2b68-666f-68d1f8082fc8', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-2.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('4248b431-1b6f-6d70-67ad-4752d111a790', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-3.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('6c40f91c-c901-0d08-d2db-1e6a0cc1bafa', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-4.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('f6a8e8eb-764c-c1fb-6294-bffd0e3e4ad3', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-5.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('7ebfcedd-5351-83af-5235-1ba73c2ac91e', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-6.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('80342e5e-4a0a-05ea-84dd-a05055856d4d', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-1.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('f5fcb0d6-7f82-ccf1-7fbf-66ea4f1fee6f', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-2.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('6352d01d-47c7-0514-2277-d7fbd82a9f37', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-3.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('e8045a13-850a-df4c-5b68-6a73cc2f489e', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-4.svg', '') ON CONFLICT (id) DO NOTHING;
INSERT INTO team (id, name, designation, photo, bio) VALUES ('5ef5ab72-1aa9-412c-e702-6a8f4d23a540', 'Guide Name TBD', 'Tour Guide', '../images/team-guide-5.svg', '') ON CONFLICT (id) DO NOTHING;

-- ============================== gallery ==============================
INSERT INTO gallery (id, image, caption, tags) VALUES ('1f905424-5289-37d9-ec84-b5f25587ab91', '../images/gallery-01.svg', 'Village Bike Tour', ARRAY['bike-tours','culture']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('3cded928-c80f-b48b-77da-c70ffee33fe0', '../images/gallery-02.svg', 'Elephant Encounter', ARRAY['wildlife']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('b17a6dc0-4d62-41c4-4544-3869c4bc7f6b', '../images/gallery-03.svg', 'Giraffe Feeding', ARRAY['wildlife']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('11d71f20-384b-fd2f-ea3a-c0959e940546', '../images/gallery-04.svg', 'Dolphin Watching', ARRAY['marine']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('60882821-027e-0713-cbd6-d0669a4d7d38', '../images/gallery-05.svg', 'Mangrove Sunset', ARRAY['marine']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('401aefa3-cda5-ed82-15a5-79313b9065f2', '../images/gallery-06.svg', 'Camel Ride on the Beach', ARRAY['marine','culture']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('cee5e258-2d81-2af5-7017-425b9fb13eda', '../images/gallery-07.svg', 'Kaya Kinondo Sacred Forest', ARRAY['culture']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('c16204d5-ea7b-2149-f8fd-f3ff224d1581', '../images/gallery-08.svg', 'Group Bike Tour', ARRAY['bike-tours']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('3f10a18f-dabb-9574-bb51-15533b104f04', '../images/gallery-09.svg', 'Tuk Tuk Coast Road', ARRAY['bike-tours','culture']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('48b8284a-c2db-cd70-edff-a31f32085964', '../images/gallery-10.svg', 'Diani Beach at Low Tide', ARRAY['marine']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('6efa9f17-11d6-fc85-f6b8-176efbaa939e', '../images/gallery-11.svg', 'Electric Bike Adventure', ARRAY['bike-tours']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('e1429efa-90e1-4102-e7e7-2d489ba3442f', '../images/gallery-12.svg', 'Local Village Culture', ARRAY['culture']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('a2833f61-5939-29fd-05da-f215de56fb13', '../images/gallery-13.svg', 'Bush Trail Ride', ARRAY['bike-tours','wildlife']::text[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery (id, image, caption, tags) VALUES ('6ba15007-ab76-1c6c-b298-2599325842e2', '../images/gallery-14.svg', 'Ocean Sunset Excursion', ARRAY['marine']::text[]) ON CONFLICT (id) DO NOTHING;

-- ============================== seo ==============================
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-index', 'index.html', 'Home', 'https://dianibike-tours.com/', 'Diani Bikes | Bike Tours, Rentals & Excursions in Diani, Watamu & Kilifi', 'Guided bike tours, mountain & electric bike rentals, tuk tuk experiences, and marine excursions across Diani, Watamu, and Kilifi — a cultural adventure on two wheels.', 'Diani Bikes | Bike Tours, Rentals & Excursions in Diani, Watamu & Kilifi', 'Guided bike tours, mountain & electric bike rentals, tuk tuk experiences, and marine excursions across Diani, Watamu, and Kilifi — a cultural adventure on two wheels.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-bike-tours', 'bike-tours.html', 'Bike Tours', 'https://dianibike-tours.com/bike-tours.html', 'Bike Tours | Diani Bikes', 'Guided bike tours through Diani and Watamu — village culture, sacred forests, and wildlife trails.', 'Bike Tours | Diani Bikes', 'Guided bike tours through Diani and Watamu — village culture, sacred forests, and wildlife trails.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-tuk-tuk', 'tuk-tuk.html', 'Tuk Tuk Experience', 'https://dianibike-tours.com/tuk-tuk.html', 'Tuk Tuk Experience | Diani Bikes', 'Cruise Diani like a local — the same cultural and nature tours by tuk tuk instead of by bike.', 'Tuk Tuk Experience | Diani Bikes', 'Cruise Diani like a local — the same cultural and nature tours by tuk tuk instead of by bike.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-marine-excursions', 'marine-excursions.html', 'Marine Excursions', 'https://dianibike-tours.com/marine-excursions.html', 'Marine Excursions | Diani Bikes', 'Dolphin watching, mangrove sundowners, camel rides, and beach tours along the Diani coast.', 'Marine Excursions | Diani Bikes', 'Dolphin watching, mangrove sundowners, camel rides, and beach tours along the Diani coast.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-forest-excursions', 'forest-excursions.html', 'Forest Excursions', 'https://dianibike-tours.com/forest-excursions.html', 'Forest Excursions | Diani Bikes', 'Wildlife encounters, ancient ruins, and conservation experiences in the forests around Diani, Watamu, and Kilifi.', 'Forest Excursions | Diani Bikes', 'Wildlife encounters, ancient ruins, and conservation experiences in the forests around Diani, Watamu, and Kilifi.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-rentals', 'rentals.html', 'Rentals', 'https://dianibike-tours.com/rentals.html', 'Bike Rentals | Diani Bikes', 'Rent mountain, electric, manual, or kids'' bikes in Diani — helmet and lock included with every rental.', 'Bike Rentals | Diani Bikes', 'Rent mountain, electric, manual, or kids'' bikes in Diani — helmet and lock included with every rental.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-about', 'about.html', 'About', 'https://dianibike-tours.com/about.html', 'About Us | Diani Bikes', 'Meet Diani Bikes — founded by Masha Kirao, a local, culturally-immersive, eco-friendly adventure operator on the Kenyan coast.', 'About Us | Diani Bikes', 'Meet Diani Bikes — founded by Masha Kirao, a local, culturally-immersive, eco-friendly adventure operator on the Kenyan coast.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-gallery', 'gallery.html', 'Gallery', 'https://dianibike-tours.com/gallery.html', 'Gallery | Diani Bikes', 'Real photos from Diani Bikes tours and excursions — village rides, wildlife, marine adventures, and the coast.', 'Gallery | Diani Bikes', 'Real photos from Diani Bikes tours and excursions — village rides, wildlife, marine adventures, and the coast.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-contact', 'contact.html', 'Contact', 'https://dianibike-tours.com/contact.html', 'Contact | Diani Bikes', 'Book a bike tour, rental, or excursion with Diani Bikes — Diani Bazaar and Jiweleupe, Watamu.', 'Contact | Diani Bikes', 'Book a bike tour, rental, or excursion with Diani Bikes — Diani Bazaar and Jiweleupe, Watamu.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-village-guided-bike-tour', 'village-guided-bike-tour.html', 'Village Guided Bike Tour', 'https://dianibike-tours.com/village-guided-bike-tour.html', 'Village Guided Bike Tour | Diani Bikes', 'Guided bike tour through local village life in Diani and Watamu — ride past homesteads, markets, and everyday coastal life with a local guide.', 'Village Guided Bike Tour | Diani Bikes', 'Guided bike tour through local village life in Diani and Watamu — ride past homesteads, markets, and everyday coastal life with a local guide.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-kaya-kinondo-sacred-forest', 'kaya-kinondo-sacred-forest.html', 'Kaya Kinondo Sacred Forest', 'https://dianibike-tours.com/kaya-kinondo-sacred-forest.html', 'Kaya Kinondo Sacred Forest | Diani Bikes', 'Guided bike ride to Kaya Kinondo, a sacred Mijikenda forest near Diani protected by the local community for generations.', 'Kaya Kinondo Sacred Forest | Diani Bikes', 'Guided bike ride to Kaya Kinondo, a sacred Mijikenda forest near Diani protected by the local community for generations.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-giraffe-feeding-adventure', 'giraffe-feeding-adventure.html', 'Giraffe Feeding Adventure', 'https://dianibike-tours.com/giraffe-feeding-adventure.html', 'Giraffe Feeding Adventure | Diani Bikes', 'Cycle to one of the Diani coast''s best-loved wildlife stops for a close, hand-feeding encounter with giraffes.', 'Giraffe Feeding Adventure | Diani Bikes', 'Cycle to one of the Diani coast''s best-loved wildlife stops for a close, hand-feeding encounter with giraffes.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-elephant-sporting', 'elephant-sporting.html', 'Elephant Sporting', 'https://dianibike-tours.com/elephant-sporting.html', 'Elephant Sporting | Diani Bikes', 'Guided ride toward Watamu to spot elephants in their natural surroundings — a highlight for wildlife lovers, by bike or tuk tuk.', 'Elephant Sporting | Diani Bikes', 'Guided ride toward Watamu to spot elephants in their natural surroundings — a highlight for wildlife lovers, by bike or tuk tuk.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-bush-tour', 'bush-tour.html', 'Bush Tour', 'https://dianibike-tours.com/bush-tour.html', 'Bush Tour | Diani Bikes', 'Rugged guided bike tour off the beaten track through the coastal bush between Diani, Kilifi, and Watamu.', 'Bush Tour | Diani Bikes', 'Rugged guided bike tour off the beaten track through the coastal bush between Diani, Kilifi, and Watamu.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-mangrove-sundowner', 'mangrove-sundowner.html', 'Mangrove Tour (Sundowner)', 'https://dianibike-tours.com/mangrove-sundowner.html', 'Mangrove Tour (Sundowner) | Diani Bikes', 'Drift through quiet mangrove channels as the sun sets over the water — one of the Diani coast''s most peaceful sundowner excursions.', 'Mangrove Tour (Sundowner) | Diani Bikes', 'Drift through quiet mangrove channels as the sun sets over the water — one of the Diani coast''s most peaceful sundowner excursions.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-full-day-private-dolphin-tour', 'full-day-private-dolphin-tour.html', 'Full Day Private Dolphin Tour', 'https://dianibike-tours.com/full-day-private-dolphin-tour.html', 'Full Day Private Dolphin Tour | Diani Bikes', 'Full-day private boat charter searching the Indian Ocean off Diani for dolphins, at your own pace with a local guide.', 'Full Day Private Dolphin Tour | Diani Bikes', 'Full-day private boat charter searching the Indian Ocean off Diani for dolphins, at your own pace with a local guide.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-camel-adventure', 'camel-adventure.html', 'Camel Adventure', 'https://dianibike-tours.com/camel-adventure.html', 'Camel Adventure | Diani Bikes', 'Relaxed guided camel ride along the white sand of Diani beach, led by an experienced local handler.', 'Camel Adventure | Diani Bikes', 'Relaxed guided camel ride along the white sand of Diani beach, led by an experienced local handler.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-beach-tour', 'beach-tour.html', 'Beach Tour', 'https://dianibike-tours.com/beach-tour.html', 'Beach Tour | Diani Bikes', 'Guided walk or ride along Diani''s beachfront, taking in the Kenyan coastline at an easy pace.', 'Beach Tour | Diani Bikes', 'Guided walk or ride along Diani''s beachfront, taking in the Kenyan coastline at an easy pace.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-snake-show-and-school', 'snake-show-and-school.html', 'Snake Show And School', 'https://dianibike-tours.com/snake-show-and-school.html', 'Snake Show And School | Diani Bikes', 'Educational, family-friendly stop near Diani and Watamu to see the coast''s native snake species up close in a safe setting.', 'Snake Show And School | Diani Bikes', 'Educational, family-friendly stop near Diani and Watamu to see the coast''s native snake species up close in a safe setting.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-ruins-of-mnarani', 'ruins-of-mnarani.html', 'Ruins of Mnarani', 'https://dianibike-tours.com/ruins-of-mnarani.html', 'Ruins of Mnarani | Diani Bikes', 'Explore the historic Mnarani ruins overlooking Kilifi Creek — remnants of a centuries-old Swahili settlement.', 'Ruins of Mnarani | Diani Bikes', 'Explore the historic Mnarani ruins overlooking Kilifi Creek — remnants of a centuries-old Swahili settlement.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-monkey-trails-and-conservation-centre', 'monkey-trails-and-conservation-centre.html', 'Monkey Trails And Conservation Centre', 'https://dianibike-tours.com/monkey-trails-and-conservation-centre.html', 'Monkey Trails And Conservation Centre | Diani Bikes', 'Guided forest walk near Diani home to local monkey populations, with a conservation-focused local guide.', 'Monkey Trails And Conservation Centre | Diani Bikes', 'Guided forest walk near Diani home to local monkey populations, with a conservation-focused local guide.') ON CONFLICT (id) DO NOTHING;
INSERT INTO seo (id, page, label, url, title, description, draft_title, draft_description) VALUES ('seo-gede-ruins-tour', 'gede-ruins-tour.html', 'Gede Ruins Tour', 'https://dianibike-tours.com/gede-ruins-tour.html', 'Gede Ruins Tour | Diani Bikes', 'Discover the ancient Swahili ruins of Gede near Watamu, one of the Kenyan coast''s best-preserved historic sites.', 'Gede Ruins Tour | Diani Bikes', 'Discover the ancient Swahili ruins of Gede near Watamu, one of the Kenyan coast''s best-preserved historic sites.') ON CONFLICT (id) DO NOTHING;
